server:
  port: 8087

spring:
  application:
    name: NOTIFICATION-SERVICE

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
