server:
  port: 8088

spring:
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
